version: '3'
services:
  app:
    image: ghcr.io/fillin-inc/rails:3.0.2-slim-bullseye
    volumes:
      - .:/opt/rails
      - bundle:/usr/local/bundle
      - node_modules:/opt/app/node_modules
    ports:
      - 3000:3000
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db
      - redis
  db:
    image: mysql:8.0
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
  redis:
    image: redis:5.0
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Tokyo

volumes:
  bundle:
  node_modules:
  database:
  redis:
